### ISSUE TITLE
请问这个报错是什么情况？

### ISSUE THREAD

**Issue by LinJie-Guo** [dubbo/dubbo-php-framework#3]
运动的demo，以下是日志
`
[2018-07-10 23:58:36,112][INFO][com\fenqile\fsof\consumer\FSOFConsumer][39] consumer cfg:{"app_name":"demo-consumer","app_src":"\/data\/web\/dubbo-php-framework\/demo\/demo-consumer\/server"}
[2018-07-10 23:58:36,113][WARN][com\fenqile\fsof\registry\automatic\ConsumerProxy][107] version:1.0.0 group:* service:com.fenqile.example.DemoService get Provider Info from redis is empty.
[2018-07-10 23:58:36,114][ERROR][com\fenqile\fsof\consumer\proxy\ProxyFactory][124] not find providers form redis for com.fenqile.example.DemoService:1.0.0:*
[2018-07-10 23:58:36,114][ERROR][com\fenqile\fsof\consumer\proxy\ProxyFactory][225] consumer_app:demo-consumer|app_config_file:/data/web/dubbo-php-framework/demo/demo-consumer/server/consumer/demo-consumer.consumer|version:1.0.0|group:*|provider_service:com.fenqile.example.DemoService|errmsg:current_address:192.168.254.111|com.fenqile.example.DemoService|exceptionmsg:Exception: current_address:192.168.254.111|com.fenqile.example.DemoService in /data/web/dubbo-php-framework/consumer/proxy/ProxyFactory.php:213
Stack trace:
#0 /data/web/dubbo-php-framework/api/FSOFApi.php(64): com\fenqile\fsof\consumer\proxy\ProxyFactory::getInstance('com.fenqile.exa...', 30)
#1 /data/web/dubbo-php-framework/demo/demo-consumer/server/Consumer.php(13): FSOFApi::newProxy('com.fenqile.exa...', 30)
#2 {main}
`

**Comment by lexin-arch** [comment]
这个错误是没有找到provider的错误，可以看下：
1、provider是否已经注册到zk？
2、consumer端的redis里面是否可以查到？

**Comment by yfh1995** [comment]
@lexin-arch 我也遇到了类似的情况，zk里是有注册的，redis里面没有查询到provider，我也没有找到往redis注册provider的代码，请问这个可能是什么原因呢

**Comment by eddiejin** [comment]
所以这个问题解决了吗?

**Comment by ova1900** [comment]
这个问题解决了吗?

**Comment by zackhu135** [comment]
@yfh1995 ,检查下agent是否有启动，启动agent的方式在wiki的快速开始文档里面搜索"Run agent"，agent会将注册中心的provider拉下来保存在本地的redis。

**Comment by zackhu135** [comment]
@ova1900 ，请参照上面的方式，检查一下agent是否有启动。

**Comment by LinJie-Guo** [comment]
原来还得装agent啊。不懂，我去搜搜看

**Comment by Machine03** [comment]
> @ova1900 ，请参照上面的方式，检查一下agent是否有启动。

能给个链接参考一下吗？

**Comment by longhtml** [comment]
agent安装了。   

/root/fsof_php_core/dubbo-php-framework/agent/log/agent/agent.2019-02-18.log  报错“2019-02-18 19:54:47.543 |FSOF_AGENT|1|connect redis timeout!|connect_redis|0”

**Comment by longhtml** [comment]
agent安装了。   

/root/fsof_php_core/dubbo-php-framework/agent/log/agent/agent.2019-02-18.log  报错“2019-02-18 19:54:47.543 |FSOF_AGENT|1|connect redis timeout!|connect_redis|0”

**Comment by jack15083** [comment]
![image](https://user-images.githubusercontent.com/2142066/54733652-a3d0d400-4bd5-11e9-9c61-e9c1f8ba517e.png)
改掉这一行重新make

**Comment by jack15083** [comment]
或者改掉fsof_global这一行的redis 配置  

![image](https://user-images.githubusercontent.com/2142066/54733948-91f03080-4bd7-11e9-8ed5-b5d8bd5cdfb1.png)

**Comment by deeprado** [comment]
@jack15083 你这个需要修改agent源码，另外可以配置redis soket 位置，配置：

unixsocket  /var/fsof/redis.sock

不过需要注意权限

**Comment by syge** [comment]
|FSOF_AGENT|22|connect zookeeper timeout!|connect_zookeeper|0
2019-04-23 16:38:13.629 |FSOF_AGENT|22|connect zookeeper timeout!|connect_zookeeper|0
2019-04-23 16:43:13.628 Now recvied alarm signal

2019-04-23 16:43:13.628 |FSOF_AGENT|-1|get zookeeper data failed!|get_zookeeper|0
2019-04-23 16:43:13.628 can't get children of key /dubbo

**Comment by syge** [comment]
请问这是什么错误

**Comment by Machine03** [comment]
检查zoo进程是什么状态？ zoo链接是否是经常超时？重启一下zoo是否可行？


------------------
国无锝不兴，人无徳不立！



 




------------------ 原始邮件 ------------------
发件人: "syge"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 下午5:47
收件人: "dubbo/dubbo-php-framework"<dubbo-php-framework@noreply.github.com>;
抄送: "゛Memory°默ぅ╃"<57789100@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [dubbo/dubbo-php-framework] 请问这个报错是什么情况？ (#3)




|FSOF_AGENT|22|connect zookeeper timeout!|connect_zookeeper|0
 2019-04-23 16:38:13.629 |FSOF_AGENT|22|connect zookeeper timeout!|connect_zookeeper|0
 2019-04-23 16:43:13.628 Now recvied alarm signal
 
2019-04-23 16:43:13.628 |FSOF_AGENT|-1|get zookeeper data failed!|get_zookeeper|0
 2019-04-23 16:43:13.628 can't get children of key /dubbo

**Comment by syge** [comment]
zookeeper是正常的，java可以正常连接注册服务和消费服务都没问题，你能留下qq么，好和你沟通
